### ISSUE TITLE
recipe for target 'spmbpOF' failed

### ISSUE THREAD

**Issue by billamiable** [yu-li/spm-bp#2]
Hi I am trying to using cmake to install, but error occurred on make:

Scanning dependencies of target spmbpOF
make[2]: Warning: File 'CMakeFiles/spmbpOF.dir/depend.make' has modification time 2.3 s in the future
[  9%] Building CXX object CMakeFiles/spmbpOF.dir/code/spmbpOF.cpp.o
[ 18%] Building CXX object CMakeFiles/spmbpOF.dir/code/FGS_Function.cpp.o
[ 27%] Building CXX object CMakeFiles/spmbpOF.dir/code/CF_Filter_Function.cpp.o
[ 36%] Building CXX object CMakeFiles/spmbpOF.dir/code/SLIC.cpp.o
[ 45%] Building CXX object CMakeFiles/spmbpOF.dir/code/Superpixels_Func.cpp.o
[ 54%] Building CXX object CMakeFiles/spmbpOF.dir/code/colorcode.cpp.o
[ 63%] Building CXX object CMakeFiles/spmbpOF.dir/code/FlowInputOutput_Func.cpp.o
[ 72%] Building CXX object CMakeFiles/spmbpOF.dir/code/Common_Datastructure_Function.cpp.o
[ 81%] Building CXX object CMakeFiles/spmbpOF.dir/code/opticalFlow.cpp.o
[ 90%] Building CXX object CMakeFiles/spmbpOF.dir/code/spmbp.cpp.o
[100%] Linking CXX executable spmbpOF
CMakeFiles/spmbpOF.dir/code/spmbp.cpp.o: In function `spm_bp::runspm_bp(cv::Mat_<cv::Vec<float, 2> >&)':
spmbp.cpp:(.text+0x5478): undefined reference to `omp_get_wtime'
spmbp.cpp:(.text+0x747f): undefined reference to `omp_get_wtime'
CMakeFiles/spmbpOF.dir/code/spmbp.cpp.o: In function `spm_bp::initiateData()':
spmbp.cpp:(.text+0x845f): undefined reference to `omp_get_wtime'
spmbp.cpp:(.text+0x9fb1): undefined reference to `omp_get_wtime'
collect2: error: ld returned 1 exit status
CMakeFiles/spmbpOF.dir/build.make:369: recipe for target 'spmbpOF' failed
make[2]: *** [spmbpOF] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/spmbpOF.dir/all' failed
make[1]: *** [CMakeFiles/spmbpOF.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I am using Ubuntu 16.04 and opencv version is 3.1.0. Do I need to change the opencv version to 3.0?Thank you !

**Comment by csukuangfj** [comment]
@billamiable 

Hi, you need to enable `openmp` while compiling.

Please add the following 3 lines to your CMakeLists.txt
```
set(my_c_flags "${my_c_flags} -fopenmp") # enable openmp
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${my_c_flags}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${my_c_flags}")
```
